//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace IoTDeploy;

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

[GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[DebuggerNonUserCode]
[CompilerGenerated]
internal class Strings
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    internal Strings() { }

    internal static ResourceManager ResourceManager
    {
        get
        {
            if (resourceMan is null)
            {
                resourceMan = new ResourceManager("IoTDeploy.Strings", typeof(Strings).Assembly);
            }
            return resourceMan;
        }
    }

    internal static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    // Program.cs
    internal static string Usage => ResourceManager.GetString("Usage", resourceCulture)!;
    internal static string ErrorInvalidArgs => ResourceManager.GetString("ErrorInvalidArgs", resourceCulture)!;
    internal static string UnknownFlag => ResourceManager.GetString("UnknownFlag", resourceCulture)!;
    internal static string MissingFlagValue => ResourceManager.GetString("MissingFlagValue", resourceCulture)!;
    internal static string ResolvingLatestArtifact => ResourceManager.GetString("ResolvingLatestArtifact", resourceCulture)!;
    internal static string ResolvedLatestArtifact => ResourceManager.GetString("ResolvedLatestArtifact", resourceCulture)!;
    internal static string NoArtifactFound => ResourceManager.GetString("NoArtifactFound", resourceCulture)!;
    internal static string ErrorConfiguration => ResourceManager.GetString("ErrorConfiguration", resourceCulture)!;
    internal static string InvalidConfiguration => ResourceManager.GetString("InvalidConfiguration", resourceCulture)!;
    internal static string ConnectingToGitHub => ResourceManager.GetString("ConnectingToGitHub", resourceCulture)!;
    internal static string DeployInfo => ResourceManager.GetString("DeployInfo", resourceCulture)!;
    internal static string WorkflowsNotFound => ResourceManager.GetString("WorkflowsNotFound", resourceCulture)!;
    internal static string WorkflowAmbiguous => ResourceManager.GetString("WorkflowAmbiguous", resourceCulture)!;
    internal static string WorkflowNotFound => ResourceManager.GetString("WorkflowNotFound", resourceCulture)!;
    internal static string DispatchFailed => ResourceManager.GetString("DispatchFailed", resourceCulture)!;
    internal static string CancellingDeploy => ResourceManager.GetString("CancellingDeploy", resourceCulture)!;
    internal static string DeploySuccess => ResourceManager.GetString("DeploySuccess", resourceCulture)!;
    internal static string DeployFailed => ResourceManager.GetString("DeployFailed", resourceCulture)!;
    internal static string DeployUnknown => ResourceManager.GetString("DeployUnknown", resourceCulture)!;
    internal static string DeployCancelled => ResourceManager.GetString("DeployCancelled", resourceCulture)!;
    internal static string TimeoutError => ResourceManager.GetString("TimeoutError", resourceCulture)!;
    internal static string DeployError => ResourceManager.GetString("DeployError", resourceCulture)!;
    internal static string AppSettingsNotFound => ResourceManager.GetString("AppSettingsNotFound", resourceCulture)!;
    internal static string AppSettingsInvalid => ResourceManager.GetString("AppSettingsInvalid", resourceCulture)!;

    // AppSettings.cs
    internal static string ValidateAppId => ResourceManager.GetString("ValidateAppId", resourceCulture)!;
    internal static string ValidateInstallationId => ResourceManager.GetString("ValidateInstallationId", resourceCulture)!;
    internal static string ValidateOwner => ResourceManager.GetString("ValidateOwner", resourceCulture)!;
    internal static string ValidatePemFilePattern => ResourceManager.GetString("ValidatePemFilePattern", resourceCulture)!;
    internal static string ValidateWorkflowTimeout => ResourceManager.GetString("ValidateWorkflowTimeout", resourceCulture)!;
    internal static string FetchingJobLabels => ResourceManager.GetString("FetchingJobLabels", resourceCulture)!;
    internal static string RequiredLabels => ResourceManager.GetString("RequiredLabels", resourceCulture)!;
    internal static string NoJobsInRun => ResourceManager.GetString("NoJobsInRun", resourceCulture)!;

    // GithubProvider.cs
    internal static string PemFileNotFound => ResourceManager.GetString("PemFileNotFound", resourceCulture)!;
    internal static string CannotReadPrivateKey => ResourceManager.GetString("CannotReadPrivateKey", resourceCulture)!;
    internal static string AuthFailed => ResourceManager.GetString("AuthFailed", resourceCulture)!;
    internal static string InstallationNotFound => ResourceManager.GetString("InstallationNotFound", resourceCulture)!;
    internal static string StartingWorkflow => ResourceManager.GetString("StartingWorkflow", resourceCulture)!;
    internal static string BranchNotFound => ResourceManager.GetString("BranchNotFound", resourceCulture)!;
    internal static string WaitingForApproval => ResourceManager.GetString("WaitingForApproval", resourceCulture)!;
    internal static string RepositoryNotFound => ResourceManager.GetString("RepositoryNotFound", resourceCulture)!;
    internal static string WaitingForWorkflow => ResourceManager.GetString("WaitingForWorkflow", resourceCulture)!;
    internal static string WorkflowTimeout => ResourceManager.GetString("WorkflowTimeout", resourceCulture)!;
    internal static string RepositoryNotFoundOrNoActions => ResourceManager.GetString("RepositoryNotFoundOrNoActions", resourceCulture)!;

    // Runner.cs
    internal static string CheckingRunnerVersion => ResourceManager.GetString("CheckingRunnerVersion", resourceCulture)!;
    internal static string DownloadingRunner => ResourceManager.GetString("DownloadingRunner", resourceCulture)!;
    internal static string RunnerAlreadyDownloaded => ResourceManager.GetString("RunnerAlreadyDownloaded", resourceCulture)!;
    internal static string ExtractingRunner => ResourceManager.GetString("ExtractingRunner", resourceCulture)!;
    internal static string ConfiguringRunner => ResourceManager.GetString("ConfiguringRunner", resourceCulture)!;
    internal static string RunnerConfigFailed => ResourceManager.GetString("RunnerConfigFailed", resourceCulture)!;
    internal static string CheckingArduinoVersion => ResourceManager.GetString("CheckingArduinoVersion", resourceCulture)!;
    internal static string DownloadingArduino => ResourceManager.GetString("DownloadingArduino", resourceCulture)!;
    internal static string ArduinoAlreadyDownloaded => ResourceManager.GetString("ArduinoAlreadyDownloaded", resourceCulture)!;
    internal static string ExtractingArduino => ResourceManager.GetString("ExtractingArduino", resourceCulture)!;
    internal static string RunnerRunning => ResourceManager.GetString("RunnerRunning", resourceCulture)!;
    internal static string RunnerFailed => ResourceManager.GetString("RunnerFailed", resourceCulture)!;
}
