//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace IoTDeployUI;

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

[GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[DebuggerNonUserCode]
[CompilerGenerated]
internal class Strings
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    internal Strings() { }

    internal static ResourceManager ResourceManager
    {
        get
        {
            if (resourceMan is null)
            {
                resourceMan = new ResourceManager("IoTDeployUI.Strings", typeof(Strings).Assembly);
            }
            return resourceMan;
        }
    }

    internal static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    // Program.cs
    internal static string ConfigErrorTitle => ResourceManager.GetString("ConfigErrorTitle", resourceCulture)!;
    internal static string InvalidConfigPrefix => ResourceManager.GetString("InvalidConfigPrefix", resourceCulture)!;
    internal static string AppSettingsNotFound => ResourceManager.GetString("AppSettingsNotFound", resourceCulture)!;
    internal static string AppSettingsInvalid => ResourceManager.GetString("AppSettingsInvalid", resourceCulture)!;

    // Form1.cs
    internal static string ConnectingToGitHub => ResourceManager.GetString("ConnectingToGitHub", resourceCulture)!;
    internal static string Ready => ResourceManager.GetString("Ready", resourceCulture)!;
    internal static string MissingKeyFileTitle => ResourceManager.GetString("MissingKeyFileTitle", resourceCulture)!;
    internal static string AuthErrorTitle => ResourceManager.GetString("AuthErrorTitle", resourceCulture)!;
    internal static string ErrorTitle => ResourceManager.GetString("ErrorTitle", resourceCulture)!;
    internal static string UnexpectedInitError => ResourceManager.GetString("UnexpectedInitError", resourceCulture)!;
    internal static string StartingDeploy => ResourceManager.GetString("StartingDeploy", resourceCulture)!;
    internal static string LoadingBranchesAndWorkflows => ResourceManager.GetString("LoadingBranchesAndWorkflows", resourceCulture)!;
    internal static string LoadErrorTitle => ResourceManager.GetString("LoadErrorTitle", resourceCulture)!;
    internal static string UnexpectedError => ResourceManager.GetString("UnexpectedError", resourceCulture)!;
    internal static string TimeoutTitle => ResourceManager.GetString("TimeoutTitle", resourceCulture)!;
    internal static string DeployErrorTitle => ResourceManager.GetString("DeployErrorTitle", resourceCulture)!;
    internal static string DeploySuccess => ResourceManager.GetString("DeploySuccess", resourceCulture)!;
    internal static string DeployCancelled => ResourceManager.GetString("DeployCancelled", resourceCulture)!;
    internal static string DeployFailed => ResourceManager.GetString("DeployFailed", resourceCulture)!;
    internal static string LogNotFound => ResourceManager.GetString("LogNotFound", resourceCulture)!;
    internal static string LogNotFoundTitle => ResourceManager.GetString("LogNotFoundTitle", resourceCulture)!;
    internal static string MissingValuesMessage => ResourceManager.GetString("MissingValuesMessage", resourceCulture)!;
    internal static string MissingValuesTitle => ResourceManager.GetString("MissingValuesTitle", resourceCulture)!;
    internal static string PortUnavailable => ResourceManager.GetString("PortUnavailable", resourceCulture)!;
    internal static string PortUnavailableTitle => ResourceManager.GetString("PortUnavailableTitle", resourceCulture)!;

    // Form1.Designer.cs
    internal static string LabelRepository => ResourceManager.GetString("LabelRepository", resourceCulture)!;
    internal static string LabelBranch => ResourceManager.GetString("LabelBranch", resourceCulture)!;
    internal static string LabelWorkflow => ResourceManager.GetString("LabelWorkflow", resourceCulture)!;
    internal static string ButtonDeploy => ResourceManager.GetString("ButtonDeploy", resourceCulture)!;
    internal static string ButtonCancel => ResourceManager.GetString("ButtonCancel", resourceCulture)!;
    internal static string ButtonLog => ResourceManager.GetString("ButtonLog", resourceCulture)!;
    internal static string LabelCom => ResourceManager.GetString("LabelCom", resourceCulture)!;
    internal static string LabelUseArtifact => ResourceManager.GetString("LabelUseArtifact", resourceCulture)!;
    internal static string FormTitle => ResourceManager.GetString("FormTitle", resourceCulture)!;

    // Artifact selector
    internal static string LoadingArtifacts => ResourceManager.GetString("LoadingArtifacts", resourceCulture)!;
    internal static string NoArtifactsAvailable => ResourceManager.GetString("NoArtifactsAvailable", resourceCulture)!;
    internal static string ArtifactsLoadFailed => ResourceManager.GetString("ArtifactsLoadFailed", resourceCulture)!;
    internal static string ArtifactItemLatest => ResourceManager.GetString("ArtifactItemLatest", resourceCulture)!;
    internal static string ArtifactItem => ResourceManager.GetString("ArtifactItem", resourceCulture)!;
    internal static string MissingArtifactSelection => ResourceManager.GetString("MissingArtifactSelection", resourceCulture)!;

    // Runner flow
    internal static string FetchingJobLabels => ResourceManager.GetString("FetchingJobLabels", resourceCulture)!;
}
